packages:
  - .
  - packages/*
catalogs:
  backend:
    drizzle-kit: ^0.31.9
    drizzle-orm: ^0.45.1
    drizzle-zod: ^0.8.3
    postgres: ^3.4.8
  dev:
    '@better-auth/cli': ^1.4.18
    autoprefixer: ^10.4.24
    bumpp: ^10.4.1
    pncat: ^0.10.2
    simple-git-hooks: ^2.13.1
    supabase: ^2.76.11
    taze: ^19.9.2
    typescript: ^5.9.3
  frontend:
    '@tailwindcss/postcss': ^4.2.0
    react: 19.2.3
    react-dom: 19.2.3
    tailwindcss: ^4.2.0
    zustand: ^5.0.11
  icons:
    lucide-react: ^0.575.0
  lint:
    '@eslint-react/eslint-plugin': ^2.13.0
    '@octohash/eslint-config': ^0.2.3
    eslint: ^9.39.3
    eslint-config-next: 16.1.4
    eslint-plugin-better-tailwindcss: ^4.3.0
    eslint-plugin-format: ^1.4.0
    eslint-plugin-react-refresh: ^0.5.0
    lint-staged: ^16.2.7
  prod:
    '@better-auth/stripe': ^1.4.18
    '@better-auth/ui': npm:@daveyplate/better-auth-ui@^3.3.15
    '@supabase/ssr': ^0.8.0
    '@supabase/supabase-js': ^2.97.0
    better-auth: ^1.4.18
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    nanoid: ^5.1.6
    next: 16.1.4
    next-intl: ^4.8.3
    next-themes: ^0.4.6
    ofetch: ^1.5.1
    radix-ui: ^1.4.3
    shadcn: ^3.8.5
    stripe: ^20.3.1
    tailwind-merge: ^3.5.0
    tw-animate-css: ^1.4.0
    usehooks-ts: ^3.1.1
    zod: ^4.3.6
  test:
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.0
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
ignoredBuiltDependencies:
  - better-sqlite3
  - core-js
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - supabase
  - unrs-resolver
  - '@parcel/watcher'
  - '@prisma/client'
  - '@swc/core'
